### ISSUE TITLE
Meaning of the prefixes

### ISSUE THREAD

**Issue by ThierryO** [YvesBas/Tadarida-D#1]
Table 2 of the documentation lists the prefixes `CM`, `CS`, `CN`, `CO` and `CO2`. Where can I find the interpretation of these prefixes? The text above the table mentions `MC`, `StE`, `UpE`, `DoE` and `StC` but those are not used elsewhere in the text.

**Comment by YvesBas** [comment]
Sorry, I did not see that we did not correct the name of these prefixes that are defined just over the table, it is corrected now!
